### ISSUE TITLE
Pretrained weights for teacher model

### ISSUE THREAD

**Issue by theTushar-dot** [Leminhbinh0209/ADD#2]
Hey there!, please provide the pretrained weights for the teacher model, the one that you have mentioned in your code. i.e., "resnet50_baseline_valacc_img128_best.pth".
PS: that is a great work guys!

**Comment by Leminhbinh0209** [comment]
Hi, you can visit here to download the teacher: https://o365skku-my.sharepoint.com/:f:/g/personal/bmle_o365_skku_edu/Ev-Gy4Wr6H9JvEtEWKDZW30Bdc5r6mTxaOLMamV5Hz6euw?e=nWNCOO
